- name: Deploy Laravel app
  hosts: laravel_server
  become: true

  vars:
    app_path: /var/www/thy-pharoth
    repo_url: https://github.com/pharoth9999/tp03-2026.git
    repo_branch: main

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: "{{ app_path }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Pull latest source code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: "{{ repo_branch }}"
        force: true

    - name: Ensure .env exists
      copy:
        src: "{{ app_path }}/.env.example"
        dest: "{{ app_path }}/.env"
        remote_src: true
        force: false

    - name: Install PHP dependencies
      command: composer install --no-dev --optimize-autoloader --no-interaction
      args:
        chdir: "{{ app_path }}"

    - name: Generate Laravel app key
      command: php artisan key:generate --force
      args:
        chdir: "{{ app_path }}"

    - name: Install Node dependencies
      command: npm install
      args:
        chdir: "{{ app_path }}"

    - name: Build frontend
      command: npm run build
      args:
        chdir: "{{ app_path }}"

    - name: Optimize Laravel
      command: php artisan optimize
      args:
        chdir: "{{ app_path }}"

    - name: Set correct permissions
      file:
        path: "{{ app_path }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Restart PHP-FPM
      service:
        name: php8.1-fpm
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted